spring:
  cloud:
    vault:
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      uri: http://localhost:8200
      kv:
        enabled: true
        backend: secret
        default-context: application

  datasource:
    url: jdbc:postgresql://localhost:5432/PromptShieldAPI
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2020

  jpa:
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  ai:
    ollama:
      chat:
        model: mistral
      base-url: http://localhost:11434

    azure:
      openai:
        api-key: ${AZURE_API_KEY}
        endpoint: https://i2200-mc1stcn4-swedencentral.cognitiveservices.azure.com/
        chat:
          options:
            deployment-name: gpt35

server:
  error:
    include-message: always
    include-binding-errors: always